"""Assemble the three paste-ready Gemini prompts from prompts/parts/.

Each prompt is one task (narrative, tables or attack forms) plus the
shared RULES, so the rules can't drift apart between them. Edit the parts,
then run:  python tools/build_prompts.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTS = ROOT / "prompts" / "parts"
OUT = {
    "1-narrative.md": ("narrative.md", "Narrative", "gemini-01.yml", "gemini-02.yml"),
    "2-tables.md": ("tables.md", "Tables", "contacts-01.md", "contacts-02.md"),
    "3-attack-forms.md": ("attack-forms.md", "TORPEDO ATTACK DATA forms", "attacks-01.md", "attacks-02.md"),
}

rules = (PARTS / "rules.md").read_text(encoding="utf-8").strip()
for name, (part, label, first, second) in OUT.items():
    body = (PARTS / part).read_text(encoding="utf-8").strip()
    text = f"""<!-- Generated by tools/build_prompts.py from prompts/parts/. Edit the parts, not this file. -->
# Gemini prompt: {label}

Start a fresh chat, paste everything between the lines, and attach the
{label.lower() if label != "TORPEDO ATTACK DATA forms" else "attack forms"} PDF. Save Gemini's answer exactly as it comes, fences
and all, in the patrol's folder as `{first}` (a further batch of pages
from the same report goes in `{second}`). See prompts/README.md for which pages to include.

---

{body}

{rules}

---
"""
    (ROOT / "prompts" / name).write_text(text, encoding="utf-8")
    print("wrote prompts/" + name)
